# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from remote_opt import forward_pb2 as remote__opt_dot_forward__pb2


class RemoteForwardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Forward = channel.unary_unary(
                '/RemoteForward/Forward',
                request_serializer=remote__opt_dot_forward__pb2.ForwardRequest.SerializeToString,
                response_deserializer=remote__opt_dot_forward__pb2.ForwardResponse.FromString,
                )


class RemoteForwardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Forward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteForwardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=remote__opt_dot_forward__pb2.ForwardRequest.FromString,
                    response_serializer=remote__opt_dot_forward__pb2.ForwardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RemoteForward', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RemoteForward(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RemoteForward/Forward',
            remote__opt_dot_forward__pb2.ForwardRequest.SerializeToString,
            remote__opt_dot_forward__pb2.ForwardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
