# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_opt/forward.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18remote_opt/forward.proto\"c\n\x0e\x46orwardRequest\x12\x1c\n\x14\x64\x65\x63oder_layer_inputs\x18\x01 \x01(\x0c\x12\x1a\n\x12next_decoder_cache\x18\x02 \x01(\x0c\x12\x17\n\x0fpast_key_values\x18\x03 \x01(\x0c\"\xa0\x01\n\x0f\x46orwardResponse\x12\x15\n\rhidden_states\x18\x01 \x01(\x0c\x12\x1a\n\x12next_decoder_cache\x18\x02 \x01(\x0c\x12\x1a\n\x12inference_latencys\x18\x03 \x03(\x02\x12\x1f\n\x17\x63ommunication_overheads\x18\x04 \x03(\x02\x12\x1d\n\x15whole_forward_latency\x18\x05 \x01(\x02\x32?\n\rRemoteForward\x12.\n\x07\x46orward\x12\x0f.ForwardRequest\x1a\x10.ForwardResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_opt.forward_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FORWARDREQUEST']._serialized_start=28
  _globals['_FORWARDREQUEST']._serialized_end=127
  _globals['_FORWARDRESPONSE']._serialized_start=130
  _globals['_FORWARDRESPONSE']._serialized_end=290
  _globals['_REMOTEFORWARD']._serialized_start=292
  _globals['_REMOTEFORWARD']._serialized_end=355
# @@protoc_insertion_point(module_scope)
